### PR TITLE
fix: sql_require_primary_key compatibility

### PR DESCRIPTION
**Pull request by gabor-boros**
In MySQL, if the `sql_require_primary_key` is turned on, no table can
exist without a primary key. Since the migration 0005 drops the primary
key field before model deletion, the table misses the primary key, hence
the migration will fail.

To prevent migration failure, we swap the primary key before dropping
the `revisionpluginrevision_ptr` field which is the actual primary key.
In case the migration need to be reverted, the opposite will happen and
we set the `revisionpluginrevision_ptr` as the primary key.

When selecting the new primary key, it doesn't really matter what we
set, since at the end of the migration we drop the whole table.

Signed-off-by: Gabor Boros <gabor.brs@gmail.com>

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @gabor-boros! I've created [OSPR-6603](https://openedx.atlassian.net/browse/OSPR-6603) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by gabor-boros** [comment]
@natabene who should be contacted for a review here? 😊

**Comment by natabene** [comment]
@gabor-boros Thank you for your contribution. @jmyatt Could you review this OSPR when you have a chance?

**Comment by gabor-boros** [comment]
@natabene @jmyatt May I help with any additional info for the review process?

**Comment by gabor-boros** [comment]
@UsamaSadiq may could help out too with reviewing 😊

**Comment by UsamaSadiq** [comment]
@gabor-boros I'll prioritise it for review within the team soon. Thanks for the PR.

**Comment by gabor-boros** [comment]
Thank you @UsamaSadiq!

**Review by UsamaSadiq — APPROVED** [review]
@gabor-boros thanks for your patience. I'll go ahead and merge this PR as well.

**Comment by natabene** [comment]
@UsamaSadiq Excited about this merge.

**Comment by openedx-webhooks** [comment]
@gabor-boros 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/django-wiki&entry.867055334=https://github.com/openedx/django-wiki/pull/116&entry.1484655318=https://github.com/gabor-boros&entry.752974735=2022-04-11+08:32&entry.1917517419=2022-06-17+14:25&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
