### PR TITLE
Add a migration for the removed ArticleSubscription model

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
@muhammad-ammar @symbolist @macdiesel @doctoryes One last migration to keep everything in sync.

**Comment by doctoryes** [comment]
@nedbat This change fixes the issue that caused us to turn off the wiki functionality, correct?

**Comment by nedbat** [comment]
This doesn't fix that issue.  This migration is needed *because* we turned off the notification functionality.  With the plugin removed from INSTALLED_APPS, these models no longer "exist".  Django 1.8 compares the installed models to the migrations, and prints a warning that they are mis-matched.  This migration makes them match.

**Comment by macdiesel** [comment]
:+1: :hamburger:

**Comment by symbolist** [comment]
@nedbat Wouldn't this cause data loss? Can we not just fix the issue?

**Comment by doctoryes** [comment]
My understanding was the same as @symbolist - I thought we were just going to re-enable it post-upgrade. The reason we disabled the wiki was it added a migration, but this adds a migration anyway.

**Comment by nedbat** [comment]
If we were to re-enable it, is it OK to just leave the table alone? Or do we need to drop it and re-add it to have the migrations be right?  I guess leaving the table alone is fine....?

**Comment by macdiesel** [comment]
My understanding is that the feature was cut and it would not be re-enabled.

**Comment by doctoryes** [comment]
OK - if the feature was cut, then let's cut it.

:+1:

**Comment by doctoryes** [comment]
BUT - let's create a ticket to remove whatever other code was attached to the feature.

**Comment by symbolist** [comment]
Since the agreement is to disable the feature permanently. :+1:

**Pull request merged**
