### PR TITLE
Remove Django deprecation message.

### PR DESCRIPTION
**Pull request by doctoryes**
Change from deprecated IPAddressField model field to the new GenericIPAddressField model field.
Bump the version number to 0.0.8.
Add migration file for the field conversion.

### CODE REVIEW

**Comment by doctoryes** [comment]
@macdiesel @nedbat @muzaffaryousaf @mattdrayer @jmbowman Please review.

@edx/devops This PR contains a DB migration FYI.

For reference, see here:
https://openedx.atlassian.net/wiki/display/PLAT/edx-platform+Django+Upgrades

There's an edx-platform PR that tests the change here: https://github.com/edx/edx-platform/pull/12944

Post-merge of this PR, I plan to create a '0.0.8' tag and fix the edx-platform PR above to use it.

**Comment by mattdrayer** [comment]
Seems like an okay change to me -- I know the guys are out on holiday this week, but tagging @saleem-latif just as an FYI

**Comment by jmbowman** [comment]
👍

**Comment by muzaffaryousaf** [comment]
👍  LGTM. Can you please close the ticket when you're done. https://openedx.atlassian.net/browse/TNL-3616

**Comment by jibsheet** [comment]
The biggest table here is 68k rows, but the alter looks like one of the ones MySQL should be able to do efficiently. 👍

**Pull request merged**
